# Jykell configuration
markdown: kramdown
highlighter: rouge
paginate: 10
language: 'en-us'

# Website info
name: 'Kris Shaffer'
description: "Digital humanist. Musician. Author. Editor. Coder."

# Author's info
author: 'Kris Shaffer'
# edit 'categories' in the front matter of every post to match this username
nickname: kris
bio: 'Kris Shaffer, Ph.D. (Yale University, 2011), will soon begin a new position as an Instructional Technology Specialist at the [University of Mary Washington](https://academics.umw.edu/dtlt/). He is currently Instructor of Music Theory at the <a href="https://music.colorado.edu">University of Coloradoâ€“Boulder</a> and Editor for <a href="http://hybrid.pub">Hybrid Pedagogy Publishing</a>. He is also the lead author of <a href="http://openmusictheory.com"><i>Open Music Theory</i></a>.'
location: 'Boulder, Colo.'
url: 'http://kris.shaffermusic.com'
root_url: 'http://kris.shaffermusic.com'
image: '/assets/images/krishead.jpg'

short_url: 'kris.shaffermusic.com'
google_analytics:
disqus:
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink:   /:year/:month/:title/
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: kshaffer
repo: jasper
branch: master
relative_source: ../
destination: ../
production_url:  http://kris.shaffermusic.com
source_url:      https://github.com/kshaffer/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
